---
- name: Ensure /etc/botgpg exist
  become: true
  ansible.builtin.file:
    path: /etc/botgpg
    state: directory
    mode: '0755'

- name: template env file
  become: true
  ansible.builtin.template:
    src: env.j2
    dest: /etc/botgpg/env
    mode: '0644'
