---
- name: Ensure docker directory exit
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: template docker-compose
  become: true
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /etc/docker/docker-compose.yml
    mode: '0644'

- name: run docker-compose 
  become: true
  ansible.builtin.shell: cd /etc/docker/ && docker compose up -d